{% set name = "d2l" %}
{% set version = "0.17.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/d2l-{{ version }}.tar.gz
  sha256: 68bff6e00119f9d9ae830347e58bfb560f0fc1b9706afe4efdc5fe390925ec50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    # cf. https://github.com/d2l-ai/d2l-en/blob/v0.17.6/setup.py#L5-L9
    - jupyter ==1.0.0
    - numpy ==1.21.5
    - matplotlib-base ==3.5.1
    - requests ==2.25.1
    - pandas ==1.2.4

test:
  imports:
    - d2l
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://d2l.ai
  dev_url: https://github.com/d2l-ai/d2l-en
  summary: Dive into Deep Learning
  license: MIT-0
  license_file: LICENSE-SAMPLECODE

extra:
  recipe-maintainers:
    - pavelzw
