{% set name = "d2l" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/d2l-{{ version }}.tar.gz
  sha256: e6c709e79fcb0ce6378ece1d080ab9ff6444e6f0f75178ad9454125e1f711284

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    # cf. https://github.com/d2l-ai/d2l-en/blob/v1.0.1/setup.py
    - jupyter ==1.0.0
    - numpy ==1.23.5
    - matplotlib-base ==3.7.2
    - requests ==2.31.0
    - pandas ==2.0.3
    - scipy ==1.10.1

test:
  imports:
    - d2l
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://d2l.ai
  dev_url: https://github.com/d2l-ai/d2l-en
  summary: Dive into Deep Learning
  license: MIT-0
  license_file: LICENSE-SAMPLECODE

extra:
  recipe-maintainers:
    - pavelzw
